config/routes.rb
Rails.application.routes.draw do
  resources :exercise_entries
  resources :exercises
  resources :workouts
  resources :users
  
  resources :users, only: [:show] do
    resources :workouts, only: [:show, :new, :edit, :destroy]
  end
  
  resources :workouts, only: [:show] do
    resources :exercise_entries, only: [:new, :edit, :destroy]
  end
  
  # get '/auth/:provider/callback' => 'sessions#create'
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  root 'application#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :exercise_entries
  has_many :exercises, through: :exercise_entries

  validates :name, presence: true
  validates :duration_mins, presence: true
  validates :user_id, presence: true
  validates :share_status, inclusion: {in: [true, false]}
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  def new
    @workout = Workout.new
  end

  def create
    @workout = current_user.workouts.build(workout_params)
    if @workout.save
      flash[:success] = "Workout successfully created!"
      redirect_to user_workout_path(current_user, @workout)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @workout.update(workout_params)
    redirect_to user_workout_path(id: @workout.id, user_id: @workout.user_id)
  end

  def destroy
    @workout.destroy
    redirect_to user_path(current_user)
  end

  private

  def workout_params
    params.require(:workout).permit(:name, :duration_mins, :share_status, :user_id)
  end

  def set_workout
    @workout = Workout.find(params[:id])
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_for(workout) do |f| %>
  <% if @workout.errors.any? %>
    <div class="form-group">
      <h3>
        <%= pluralize(@workout.errors.count, "error") %> found:
      </h3>

      <ul>
        <% @workout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.hidden_field :user_id %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :duration_mins, "Duration(mins)" %>
    <%= f.number_field :duration_mins, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.check_box :share_status %>
    <%= f.label :share_status, "Share Workout", class: "checkbox"%>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn workout-btn" %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<section id="workout-form">
  <div class="form-container">
    <div class="form-content">
      <h1>Edit Workout</h1>
      <%= render partial: 'form', locals: { workout: @workout } %>
    </div>
  </div>
</section>

app/views/workouts/new.html.erb
<section id="workout-form">
  <div class="form-container">
    <div class="form-content">
      <h1>New Workout</h1>
      <%= render partial: 'form', locals: { workout: @workout } %>
    </div>
  </div>
</section>

app/views/workouts/show.html.erb
<section id="workout-page">
  <div class="workout-container">
    <div class="flex-container">
      <div class="flex-item">
        <h1><%= @workout.name %></h1>
      </div>

      <div class="flex-item">
        <% if @workout.user == current_user %>
          <%= link_to "Edit Workout", edit_user_workout_path(current_user), class: "btn edit-btn" %>

          <%= link_to "Delete Workout", user_workout_path(@workout.user, @workout), method: :delete, class: "btn delete-btn" %>
        <% end %>
      </div>
    </div>
    
    <h3>Duration: <%= @workout.duration_mins %> minutes</h3>

    <table>
      <thead>
        <tr>
          <th>Exercise</th>
          <th>Sets</th>
          <th>Reps</th>
          <th>Weight (lbs)</th>
          <th>Rating</th>
          <th>Notes</th>
          <% if @workout.user == current_user %>
            <th><%= link_to "Add Exercise", new_workout_exercise_entry_path(@workout), class: "btn exercise-btn" %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @workout.exercise_entries.each do |exercise_entry| %>
        <tr>
          <td><%= exercise_entry.exercise.name %></td>
          <td><%= exercise_entry.sets %></td>
          <td><%= exercise_entry.reps %></td>
          <td><%= exercise_entry.weight_lbs %></td>
          <td><%= exercise_entry.exercise_rating %></td>
          <td><%= exercise_entry.notes %></td>
          <% if @workout.user == current_user %>
            <td>
                <%= link_to "Edit", edit_workout_exercise_entry_path(id: exercise_entry.id, workout_id: exercise_entry.workout_id), class: "btn entry-btn" %>
                  
                <%= link_to "Delete", workout_exercise_entry_path(id: exercise_entry.id, workout_id: exercise_entry.workout_id), method: :delete, class: "btn entry-btn" %>
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>