config/routes.rb
Rails.application.routes.draw do
  resources :exercise_entries
  resources :exercises
  resources :workouts
  resources :users
  
  resources :users, only: [:show] do
    resources :workouts, only: [:show, :new, :edit, :destroy]
  end
  
  resources :workouts, only: [:show] do
    resources :exercise_entries, only: [:new, :edit, :destroy]
  end
  
  # get '/auth/:provider/callback' => 'sessions#create'
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  root 'application#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :workouts
  has_many :exercises, through: :workouts
  has_many :exercise_entries, through: :workouts

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :password, length: { minimum: 6 }
  
  def self.find_or_create_by_omniauth(auth_hash)
    self.where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create do |user|
      user.provider = auth_hash.provider
      user.uid = auth_hash.uid
      user.email = auth_hash.info.email
      user.first_name = auth_hash.info.first_name
      user.last_name = auth_hash.info.last_name
      user.password = SecureRandom.hex
    end
  end

  def full_name
    @full_name = "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_if_not_logged_in
    @users = User.all
  end

  def new #signup
    redirect_if_logged_in
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You have signed in!"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    redirect_if_not_logged_in
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<section id="user-index">
  <div class="index-container">
    <div class="index-content">
      <h1>User Index</h1>

      <ul class="list-group">
        <% if current_user.id == 1 %>
          <% @users.each do |user| %>
            <li><%= link_to user.full_name, user_path(user) %></li>
          <% end %>
        <% else %>
          <% @users.where.not(id: 1).each do |user| %>
            <li><%= link_to user.full_name, user_path(user) %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

</section>

app/views/users/new.html.erb
<section id="signup-form">
  <div class="signup-container">
    <div class="signup-content">
      <%= form_for(@user) do |f| %>
        <div class='form-group'>
          <% if @user.errors.any? %>
            <h2><%= pluralize(@user.errors.count, "error") %> found:</h2>

            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        
        <div class="form-group">
          <%= f.label :first_name, "First Name" %>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :last_name, "Last Name" %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.submit "SIGN UP", class: "btn signup-btn" %>
        </div>
      <% end %>

      <ul>
        <li class="signup-link"><%= link_to('Sign Up with Facebook', '/auth/facebook', method: :post) %></li>
        <li class="signup-link"><%= link_to('Sign Up with Google', '/auth/google_oauth2', method: :post) %></li>
      </ul>
    </div>
  </div>

</section>
  

app/views/users/show.html.erb
<section id="profile">
  <div class="profile-container">
    <div class="user-info">
      <% if @user == current_user %>
        <h1>Hi, <%= @user.first_name %>.</h1>
      <% else %>
        <h1><%= @user.first_name %>'s Profile</h1>
      <% end %>

      <ul>
        <li>Name: <%= @user.full_name %></li>
        <li>Email: <%= @user.email %></li>
      </ul>
    </div>

    <div class="flex-container">
      <div class="flex-item">
        <h3>Shared Workouts</h3>
        <ul>
        <% @user.workouts.where(share_status: true).order(created_at: :desc).each do |workout| %>
          <li><%= link_to "#{workout.created_at.in_time_zone("America/New_York").strftime("%A - %m/%d/%Y - %l:%M %p")} - #{workout.name}", user_workout_path(user_id: workout.user_id, id: workout.id) %></li>
        <% end %>
        </ul>
      </div>

      <div class="flex-item">
        <% if @user == current_user %>
        <h3>Private Workouts</h3>
        <ul>
          <% @user.workouts.where(share_status: false).order(created_at: :desc).each do |workout| %>
            <li><%= link_to "#{workout.created_at.in_time_zone("America/New_York").strftime("%A - %m/%d/%Y - %l:%M %p")} - #{workout.name}", user_workout_path(user_id: workout.user_id, id: workout.id) %></li>
          <% end %>
        <% end %>
        </ul>
      </div>
  </div>
</section>