config/routes.rb
Rails.application.routes.draw do
  resources :exercise_entries
  resources :exercises
  resources :workouts
  resources :users
  
  resources :users, only: [:show] do
    resources :workouts, only: [:show, :new, :edit, :destroy]
  end
  
  resources :workouts, only: [:show] do
    resources :exercise_entries, only: [:new, :edit, :destroy]
  end
  
  # get '/auth/:provider/callback' => 'sessions#create'
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  root 'application#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update]

  def index
    if !params[:category].blank?
      @exercises = Exercise.by_category(params[:category])
    else
      @exercises = Exercise.all
    end
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.create(exercise_params)
    redirect_to exercise_path(@exercise)
  end

  def show
  end

  def edit
  end

  def update
    @exercise.update(exercise_params)
    redirect_to exercise_path(@exercise)
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name, :description, :category)
  end

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<% if @exercise_entry.errors.any? %>
  <h3>
    <%= pluralize(@exercise_entry.errors.count, "error") %> found:
  </h3>

  <ul>
    <% @exercise_entry.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for exercise do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category, ['Chest', 'Shoulders', 'Arms', 'Back', 'Legs', 'Abs', 'Cardio'], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn" %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<%= render partial: 'form', locals: {exercise: @exercise} %>

app/views/exercises/index.html.erb
<section id="exercise-index">
  <div class="index-container">
    <div class="index-content">
      <h1>Exercise Index</h1>

      <%= form_tag('/exercises', method: 'get') do %>
        <%= select_tag 'category', options_for_select(['Chest', 'Shoulders', 'Arms', 'Back', 'Legs', 'Abs', 'Cardio']), include_blank: "All Categories", class: "dropdown" %>
        <%= submit_tag "Filter", class: "btn filter" %>
      <% end %>

      <ul class="list-group mt-3">
        <% @exercises.each do |exercise| %>
          <li class="list-group-item list-group-item-action"><%= link_to exercise.name, exercise_path(exercise) %></li>
        <% end %>
      </ul>

      <% if current_user.id == 1 %>
        <%= link_to "Create New Exercise", new_exercise_path, class: "btn" %>
      <% end %>
    </div>
  </div>
</section>

app/views/exercises/new.html.erb
<%= render partial: 'form', locals: {exercise: @exercise} %>

app/views/exercises/show.html.erb
<section id="exercise-show">
  <div class="exercise-container">
    <div class="exercise-details">
      <h1><%= @exercise.name %></h1>
      <div class="sub-header">
        <h2>Category: <%= @exercise.category %></h2>
        <h2>Average User Rating: <%= @exercise.avg_rating %></h2>
      </div>
      <h3>Description:</h3>
      <p><%= @exercise.description %></p>

      <% if current_user.id == 1 %>
        <%= link_to "Edit Exercise", edit_exercise_path(@exercise), class: "btn btn-secondary" %>
      <% end %>

      <%= link_to "Exercise Index", exercises_path, class: "btn show-btn" %>
  </div>
</section>