config/routes.rb
Rails.application.routes.draw do
  resources :exercise_entries
  resources :exercises
  resources :workouts
  resources :users
  
  resources :users, only: [:show] do
    resources :workouts, only: [:show, :new, :edit, :destroy]
  end
  
  resources :workouts, only: [:show] do
    resources :exercise_entries, only: [:new, :edit, :destroy]
  end
  
  # get '/auth/:provider/callback' => 'sessions#create'
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  root 'application#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <% if type == "success"%>
    <div class="flash-container">
      <p class="success"><%= message %></p>
    </div>
  <% elsif type == "error"%>
    <div class="flash-container">
      <p class="error"><%= message %></p>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<nav id="navbar">
  <% if !logged_in? && current_page?(root_path) %>
    <div></div>
    <ul>
      <li><%= link_to "LOG IN", login_path %></li>
      <li><%= link_to "SIGN UP", new_user_path %></li>
    </ul>
  <% elsif !logged_in? %>
    <%= link_to "FIT BUDDY", root_path, class: "logo" %>
    <ul>
      <li><%= link_to "LOG IN", login_path %></li>
      <li><%= link_to "SIGN UP", new_user_path %></li>
    </ul>
  <% else %>
    <%= link_to "FIT BUDDY", root_path, class: "logo" %>
    <ul>
      <li><%= link_to "LOG WORKOUT", new_user_workout_path(current_user) %></li>
      <li><%= link_to "PROFILE", user_path(current_user) %></li>
      <li><%= link_to "LOG OUT", logout_path, method: :post %></li>
    </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitBuddy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= render "layouts/flash_messages" %>
    <%= yield %>
    
  </body>
</html>